# spring config
server:
  port: 80 #server port
spring:
  thymeleaf:
    cache: false #关闭模板引擎缓存
  datasource: #数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abcd0123
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC


community:
  github:
    clientId: 088456cd97b4eb2a2bbf
    redirectUri: http://localhost/authorizedCallback
    scope: user
    clientSecret: 50fe47b4e7ab5238523b3e9d35a750f9498c57b5
    accessTokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
  web:
    maxAge: 1800 #保存半个小时
    path: /
mybatis:
  type-aliases-package: com.me.community.pojo
  mapper-locations: classpath:mappers/*.xml
